/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  communitySidebar: [
    {
      type: 'category',
      label: 'Community Solutions',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'community',
        },
      ],
    },
  ],
  partnerSidebar: [
    {
      type: 'category',
      label: 'Partner Solutions',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'partners',
        },
      ],
    },
  ],
  standardsSidebar: [
    `standards/overview`,
    'standards/requirements',
      {
        type: 'category',
        label: 'Coding Standards',
        collapsible: true,
        items: [
          {
            type: 'autogenerated',
            dirName: 'standards/coding-standards',
          },
        ],
      },
   `standards/uninstall-guide`,
    ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
